### ISSUE TITLE
Expose displayMode modifiable properties

### ISSUE THREAD

**Issue by Mx-Iris** [dagronf/DSFToolbar#2]
So if I need to change displayMode I'm going to do this
```
view.window?.toolbar?.displayMode = .iconOnly
```

**Comment by dagronf** [comment]
Hey @Mx-Iris, I've just pushed up a new version (4.0.0) which exposes the display mode

I had to bump the minimum macOS version to 10.13, as I don't have an Xcode version that supports the older 10.12 version previously.  If this is an issue, let me know and I'll deal with it.  Ultimately, my plan is to drop all macos versions that aren't supported by the current xcode version.

There are two ways to set the display mode.

Simple: 
`myToolbar.displayMode(.iconOnly)`

Binding (so you can two-way update using a value binder)

`myToolbar.bindDisplayMode(self.primaryViewController.displayModeBinder)`

Let me know how you go.

**Comment by Mx-Iris** [comment]
Good job, my problem is solved, please close this issue
